name: "Docs: Release to GitHub pages"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docs-release.yaml"
      - ".ci/mkdocs/mkdocs.yml"
      - "docs/**"

permissions:
  contents: write

jobs:
  release-docs:
    name: Release documentation
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: "Generate Short Lived OAuth App Token (ghs_*)"
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout main branch
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
        with:
          python-version: 3.x

      - name: Install requirements
        run: pip install -r docs/requirements.txt

      - name: Build and publish docs
        run: mkdocs build -f .ci/mkdocs/mkdocs.yml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          publish_dir: ./site
          destination_dir: .
          user_name: "repo-jeeves[bot]"
          user_email: "repo-jeeves <106431701+repo-jeeves[bot]@users.noreply.github.com>"
